HOSTDEV-3478 Relocatable Python 3.11.x
Fixed JIRA tickets:
HOSTDEV-3478 Relocatable Python 3.11.x
HOSTDEV-3486 AIX build failed: cannot use gawk builtin `namespace' as variable name
HOSTDEV-3488 RHEL 64-bit: Could not find platform dependent libraries <exec_prefix>
HOSTDEV-3489 cc1: error: unrecognized command line option "-std=c11"
HOSTDEV-3490 OpenSSL >= 1.1.1 is required for python 3.11
HOSTDEV-3491 Perl v5.10.0 is required to build OpenSSL v1.1.1
HOSTDEV-3492 Perl build error: too few arguments to function 'dbmclose'
HOSTDEV-3493 Compile warnings: Falling back to the standard locale ("C")
HOSTDEV-3494 Cannot build with both -Duserelocatableinc and -Duseshrplib on Solaris
HOSTDEV-3495 OpenSSL 1.1.1: undefined symbol clock_gettime on Solaris 10 x64
HOSTDEV-3497 configure: error: Unknown float word ordering on Solaris
HOSTDEV-3498 Python build: ld fatal unrecognized option '--' on Solaris
HOSTDEV-3502 Added a patch for zstd compression library
HOSTDEV-3512 Python 3.11 test_xml_etree failed
HOSTDEV-3513 Security fixes for libexpat
HOSTDEV-3514 Add BLAKE2 hash library
HOSTDEV-3515 Add libuuid to fast generate unique identifiers
HOSTDEV-3516 Runtime library path is incorrect for many dependencies of relocatable python
HOSTDEV-3517 libevent test suite failed
HOSTDEV-3524 Python on SLES: readline: /etc/inputrc: line 19: term: unknown variable name

Changes:
* Use external URL to download Python sources
* Update libgpg-error 1.10 => 1.47 to fix known issue with GNU awk.
* Update Python 3.8.12 => 3.11.7
* Remove obsoleted patches
* Remove --with-gcc option:
  configure: WARNING: unrecognized options: --with-gcc
  this option was removed few years ago
* Use recommended platlibdir configuration option for 64-bit platforms
* Use C std=99
* Use C locale settings
* Remove static_assert macro
* Build OpenSSL v1.1.1 for all platforms
* Remove outdated OpenSSL patches
* Add Path for current env
* Disable ODBM_File Perl extention
  Known issue, reference: https://github.com/Perl/perl5/issues/9609
* Disable shared libperl, because we need relocatable perl
* Add a patch for linker
* Added librt to build OpenSSL on Solaris
* Use right grep command found by configure script
* Fix typo in the configure script
* Fix zstd compression library on AIX and Solaris
* Fix readline exported symbols on AIX

Signed-off-by: Alex Deiter <adeiter@infinidat.com>